name: 'Terraform Apply'

on: [push]

env:
  TF_LOG: INFO

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    # Set the working directory to main for the config files
    defaults:
      run:
        shell: bash
        working-directory: ./azure

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the preferred version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.2

    # Logs in with your Azure credentials
    - name: Azure login
      uses: azure/login@v1.4.6
      with:
        creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL_CREDS }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      id: init
    #   env:
    #     ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    #     ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    #     ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    #     ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #     RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
    #     STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
    #     CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
      run: terraform init

      # On push to main, build or change infrastructure according to Terraform configuration files
    - name: Terraform Apply
    #   if: github.event_name == 'push'
    #   env:
    #     ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
    #     ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
    #     ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    #     ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      run: terraform apply -auto-approve