name: 'Terraform Destroy'

on:
  schedule:
    - cron: '0-6 2 * * *'
  workflow_dispatch:
  
env:
  TF_LOG: INFO

jobs:
  azure_terraform:
    name: 'Azure - Terraform deploy'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    # Set the working directory to main for the config files
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the preferred version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.7.2

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      id: init
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_SERVICE_PRINCIPAL_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_SERVICE_PRINCIPAL_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.AZURE_SERVICE_PRINCIPAL_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SERVICE_PRINCIPAL_SUBSCRIPTION_ID }}
        RESOURCE_GROUP: ${{ secrets.AZURE_TF_STATE_RESOURCE_GROUP }}
        STORAGE_ACCOUNT: ${{ secrets.AZURE_TF_STATE_STORAGE_ACCOUNT }}
        CONTAINER_NAME: ${{ secrets.AZURE_TF_STATE_CONTAINER_NAME }}
      run: terraform init -backend-config="storage_account_name=$STORAGE_ACCOUNT" -backend-config="container_name=$CONTAINER_NAME" -backend-config="resource_group_name=$RESOURCE_GROUP"

      # On push to main, build or change infrastructure according to Terraform configuration files
    - name: Terraform Destroy
      id: destroy
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_SERVICE_PRINCIPAL_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_SERVICE_PRINCIPAL_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.AZURE_SERVICE_PRINCIPAL_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SERVICE_PRINCIPAL_SUBSCRIPTION_ID }}
        TF_VAR_main_database_connectionstring: ""
        TF_VAR_cart_database_connectionstring: ""
        TF_VAR_authentication_secret_key: ""
      run: terraform destroy -auto-approve
