name: 'Terraform Destroy'

on:
    schedule:
        - cron: 0 22 * * *

env:
  TF_LOG: INFO

jobs:
  azure_terraform:
    name: 'Azure - Terraform deploy'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    # Set the working directory to main for the config files
    defaults:
      run:
        shell: bash
        working-directory: ./azure

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the preferred version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.2

    # Logs in with your Azure credentials
    - name: Azure login
      uses: azure/login@v1.4.6
      with:
        creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL_CREDS }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      id: init
      run: terraform init

      # On push to main, build or change infrastructure according to Terraform configuration files
    - name: Terraform Destroy
      id: destroy
      run: terraform destroy -auto-approve